/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

/**
 *
 * @author josephrunser
 */
public class LessonTwoPanel extends javax.swing.JPanel {
    
    PanelManager manager;

    /**
     * Creates new form LessonTwoPanel
     * 
     * @param manager
     */
    public LessonTwoPanel(PanelManager manager) {
        initComponents();
        
        this.manager = manager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_previousLesson = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btn_previousLesson.setText("Previous Lesson");
        btn_previousLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_previousLessonActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_previousLesson)
                .addContainerGap(267, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(btn_previousLesson)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_previousLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previousLessonActionPerformed
        
        manager.setPanel(PanelManager.INDEX_LESSON_ONE);
        
    }//GEN-LAST:event_btn_previousLessonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_previousLesson;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
